//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnrollmentEntities : DbContext
    {
        public EnrollmentEntities()
            : base("name=EnrollmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckBoxViewModel> CheckBoxViewModels { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<ProfessorViewModel> ProfessorViewModels { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject1> Subject1 { get; set; }
        public virtual DbSet<SubjectToProf> SubjectToProfs { get; set; }
    }
}
